language: android
sudo: required
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-26
before_install:
  - chmod +x ./gradlew
script:
  - "./gradlew clean build"
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'