language: android
sudo: required
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.0
  - echo y | android update sdk -u -a -t android-26
before_install:
  - chmod +x ./gradlew
script:
  - "./gradlew clean build"